language: node_js
dist: xenial
sudo: required

matrix:
  include:
    - name: Postgresql 9.6 - Node.JS 10
      node_js: "10"
      addons:
        postgresql: "9.6"
    - name: Postgresql 10 - Node.JS 10
      node_js: "10"
      addons:
        postgresql: "10"
    - name: Postgresql 11 - Node.JS 10
      node_js: "10"
      env:
        - INSTALL_PG_11=true
      addons:
        postgresql: "11"
    - name: Postgresql 12 - Node.JS 10
      node_js: "10"
      env:
        - INSTALL_PG_12=true
      addons:
        postgresql: "11"
    - name: Postgresql 9.6 - Node.JS 12
      node_js: "12"
      addons:
        postgresql: "9.6"
    - name: Postgresql 10 - Node.JS 12
      node_js: "12"
      addons:
        postgresql: "10"
    - name: Postgresql 11 - Node.JS 12
      node_js: "12"
      env:
        - INSTALL_PG_11=true
      addons:
        postgresql: "11"
    - name: Postgresql 12 - Node.JS 12
      node_js: "12"
      env:
        - INSTALL_PG_12=true
      addons:
        postgresql: "12"

before_install:
  - | 
    if [[ "$INSTALL_PG_11" == "true" ]]; then
      sudo apt-get update
      sudo apt-get --yes remove postgresql\*
      sudo apt-get install -y postgresql-11 postgresql-client-11
      sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
      sudo service postgresql restart 11  
    fi
    if [[ "$INSTALL_PG_12" == "true" ]]; then
      sudo apt-get update
      sudo apt-get --yes remove postgresql\*
      sudo apt-get install -y postgresql-12 postgresql-client-12
      sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
      sudo service postgresql restart 12  
    fi

env:
  global:
    - PGUSER=postgres
    - PGPASSWORD=postgres
    - PGPORT=5432

before_script:
  - psql -c 'create database graphile_worker_test' -U postgres

script:
  - psql -c "SELECT version();"
  - yarn lint
  - yarn test
